export const INITIAL_INCIDENTS = [
  {
    id: 'INC-029',
    service: 'Production API Gateway',
    severity: 'High',
    title: 'Production API unavailable',
    summary: '503 errors detected across Asia region',
    status: 'Investigating',
    startedAt: 'Last updated 2 min ago',
    detectedTimestamp: '2026-09-29T14:48:00Z',
    blastRadius: '12,500 customers affected across Asia-Pacific region',
    customersAffected: '12,500',
    regions: 'Asia-Pacific (Tokyo, Singapore)',
    errorRate: '34% HTTP 503',
    evidenceSnippet: `503 Service Unavailable\nPOST /api/orders\nConnection timeout\nDatabase connection pool exhausted (active: 100/100, waiting: 142)`,
    correlation: {
      memoryId: 'MEM-012',
      memoryTitle: 'PostgreSQL Connection Pool Saturation',
      memoryDate: 'July 14, 2026',
      similarity: 89,
      sharedSignals: [
        { current: '503 Service Unavailable', historical: 'Database connection exhaustion', signal: 'Connection pool saturation' },
        { current: 'Spike during batch order flow', historical: 'Unindexed reporting query lock', signal: 'Long-running transaction holding pool slots' },
        { current: 'PgBouncer queue timeout >5000ms', historical: 'Client connection queue starvation', signal: 'Pool exhaustion failure pattern' },
      ],
      rootCauseTitle: 'Database connection pool saturation',
      whatWeFound: 'Long-running transactions consumed available database connections, preventing new API requests from obtaining a connection.',
      evidencePoints: [
        'Connection pool saturation (100% active sockets occupied)',
        'Long-running transaction holding row locks in order_receipts',
        'Matching historical failure pattern with MEM-012',
      ],
      historicalEvidence: 'MEM-012 experienced the same failure pattern during high-volume batch processing.',
      recoverySubtitle: 'Actions derived from the documented resolution of MEM-012.',
      recoverySteps: [
        {
          id: 1,
          stepNumber: '01',
          title: 'Verify connection pool usage',
          description: 'Check whether active connections have reached the configured limit in PgBouncer pooler.',
          expectedOutcome: 'Confirm pool saturation versus database engine crash.',
          status: 'completed',
        },
        {
          id: 2,
          stepNumber: '02',
          title: 'Identify long-running transactions',
          description: 'Find active backend sessions holding table locks unexpectedly longer than 15 seconds.',
          expectedOutcome: 'Pinpoint blocking queries and idle-in-transaction connection leaks.',
          status: 'completed',
        },
        {
          id: 3,
          stepNumber: '03',
          title: 'Apply the approved recovery',
          description: 'Increase pool capacity dynamically to 200 and terminate idle-in-transaction connections.',
          expectedOutcome: 'Restore order creation endpoint availability and lower p99 latency below 120ms.',
          status: 'in_progress',
        },
      ],
      resolutionSummary: {
        problem: '503 errors affecting production API across Asia-Pacific region',
        rootCause: 'Database connection pool saturation caused by unindexed order reconciliation queries',
        resolution: 'Connection pool capacity increased to 200, idle transactions terminated, and read queries redirected to read replica',
        lessonLearned: 'Separate reporting and audit workloads from transactional user checkout workloads.',
      },
    },
  },
  {
    id: 'INC-028',
    service: 'Payment Processing Service',
    severity: 'Medium',
    title: 'Payment checkout webhook latency elevation',
    summary: 'p99 response time degraded from 180ms to 2,400ms',
    status: 'Resolved',
    startedAt: '3 hours ago',
    detectedTimestamp: '2026-09-29T11:30:00Z',
    blastRadius: '3,200 checkout attempts experienced delayed confirmation',
    customersAffected: '3,200',
    regions: 'US-East',
    errorRate: '4.2% timeout',
    evidenceSnippet: `HTTP 504 Gateway Timeout\nPOST /v1/payments/verify\nUpstream partner bank handshake delayed`,
    correlation: {
      memoryId: 'MEM-008',
      memoryTitle: 'Payment Gateway Partner Latency Spillover',
      memoryDate: 'May 20, 2026',
      similarity: 92,
      sharedSignals: [
        { current: 'Delayed verification webhook', historical: 'Partner upstream rate-limiting', signal: 'External dependency backpressure' },
      ],
      rootCauseTitle: 'Upstream banking partner gateway rate limit',
      whatWeFound: 'Banking partner throttled concurrent webhook validation requests without backoff.',
      evidencePoints: [
        'External partner HTTP 429 throttling',
        'Worker thread pool depletion',
      ],
      historicalEvidence: 'MEM-008 resolved this by activating the secondary fallback acquirer route.',
      recoverySubtitle: 'Derived from MEM-008 partner failover runbook.',
      recoverySteps: [
        { id: 1, stepNumber: '01', title: 'Verify acquirer error distribution', description: 'Inspect error codes from primary acquirer.', status: 'completed' },
        { id: 2, stepNumber: '02', title: 'Route traffic to secondary acquirer', description: 'Enable traffic shift to backup payment processor.', status: 'completed' },
      ],
      resolutionSummary: {
        problem: 'Payment checkout webhook latency elevation',
        rootCause: 'Primary acquirer partner throughput rate limit',
        resolution: 'Shifted 70% of payment verification volume to secondary gateway route',
        lessonLearned: 'Always maintain dual-acquirer hot-standby routing for payment webhooks.',
      },
    },
  },
  {
    id: 'INC-027',
    service: 'Authentication Microservice',
    severity: 'High',
    title: 'OAuth session token validation failures',
    summary: 'Intermittent 401 Unauthorized errors during token refresh',
    status: 'Resolved',
    startedAt: 'Yesterday',
    detectedTimestamp: '2026-09-28T16:15:00Z',
    blastRadius: '4,800 mobile app user sessions invalidated',
    customersAffected: '4,800',
    regions: 'Global',
    errorRate: '18% token rejection',
    evidenceSnippet: `JWT verification error: Key ID not found in JWKS cache\nRedis session store replica lagging by 45s`,
    correlation: {
      memoryId: 'MEM-007',
      memoryTitle: 'Redis Session Store Replication Lag',
      memoryDate: 'April 02, 2026',
      similarity: 94,
      sharedSignals: [
        { current: 'JWKS key verification error', historical: 'Stale cache on read replica', signal: 'Distributed cache sync lag' },
      ],
      rootCauseTitle: 'Redis replica sync lag during key rotation',
      whatWeFound: 'Read-only Redis replicas were 45s behind master during automated key rotation cycle.',
      evidencePoints: [
        'Redis replica replication offset delay',
        'JWKS cache miss on newly issued signing key',
      ],
      historicalEvidence: 'MEM-007 documented the same replica sync delay during security rotation.',
      recoverySubtitle: 'Derived from MEM-007 cache synchronization procedure.',
      recoverySteps: [
        { id: 1, stepNumber: '01', title: 'Bypass lagging read replicas', description: 'Point authentication middleware directly to Redis master.', status: 'completed' },
        { id: 2, stepNumber: '02', title: 'Warm public key cache', description: 'Pre-populate public keys across all regional edge pods.', status: 'completed' },
      ],
      resolutionSummary: {
        problem: 'OAuth session token validation failures',
        rootCause: 'Redis replica synchronization delay during signing key rotation',
        resolution: 'Bypassed lagging replicas and pre-warmed edge key caches',
        lessonLearned: 'Enforce synchronous replication for security credential rotation.',
      },
    },
  },
  {
    id: 'INC-026',
    service: 'Notification Worker',
    severity: 'Medium',
    title: 'Customer push notification delivery backlog',
    summary: 'Message queue processing delay of 35 minutes',
    status: 'Resolved',
    startedAt: '3 days ago',
    detectedTimestamp: '2026-09-26T09:40:00Z',
    blastRadius: 'Delivery delays for order confirmation notifications',
    customersAffected: '8,400',
    regions: 'Europe-West',
    errorRate: 'Queue depth: 85,000 backlog',
    evidenceSnippet: `Kafka consumer partition lag: 85,200\nDownstream vendor rate limited`,
    correlation: {
      memoryId: 'MEM-004',
      memoryTitle: 'Kafka Consumer Partition Unbalance',
      memoryDate: 'February 18, 2026',
      similarity: 88,
      sharedSignals: [
        { current: 'Queue backlog accumulation', historical: 'Consumer thread starvation', signal: 'Worker throughput bottleneck' },
      ],
      rootCauseTitle: 'Consumer thread starvation on external webhook',
      whatWeFound: 'Synchronous HTTP calls to external webhook provider stalled message ingestion threads.',
      evidencePoints: [
        'Single consumer thread blocked on external timeout',
        'Partition rebalance thrashing',
      ],
      historicalEvidence: 'MEM-004 resolved this by decoupling webhook calls into an asynchronous thread pool.',
      recoverySubtitle: 'Derived from MEM-004 queue offload playbook.',
      recoverySteps: [
        { id: 1, stepNumber: '01', title: 'Scale worker pods from 4 to 12', description: 'Add consumer instances to clear partition backlog.', status: 'completed' },
      ],
      resolutionSummary: {
        problem: 'Customer push notification delivery backlog',
        rootCause: 'Synchronous blocking I/O on external notification provider',
        resolution: 'Scaled worker pool and decoupled external delivery onto async worker queue',
        lessonLearned: 'Never execute third-party API calls directly on the Kafka ingestion loop.',
      },
    },
  },
];

export const INITIAL_MEMORIES = [
  {
    id: 'MEM-012',
    title: 'PostgreSQL Connection Pool Saturation',
    date: 'July 14, 2026',
    category: 'Database',
    service: 'Production Database Cluster',
    rootCause: 'Long-running transactions consumed available database connections, preventing new API requests from obtaining a connection.',
    resolution: 'Increased connection pool capacity and configured idle session timeout thresholds in PgBouncer.',
    lesson: 'Separate reporting workloads from transactional workloads to prevent shared lock contention.',
    impact: '18 minutes of 503 errors on customer checkout API',
    relatedIncidents: ['INC-029', 'INC-012'],
  },
  {
    id: 'MEM-008',
    title: 'Payment Gateway Partner Latency Spillover',
    date: 'May 20, 2026',
    category: 'API',
    service: 'Payment Processing Service',
    rootCause: 'Third-party acquirer partner experienced transient upstream latency, depleting client worker thread pools.',
    resolution: 'Activated circuit breaker and automatically shifted 70% of payment validation volume to secondary acquirer.',
    lesson: 'Always maintain dual-acquirer hot-standby routing for payment webhooks.',
    impact: 'Elevated checkout latency for 3,200 transactions',
    relatedIncidents: ['INC-028'],
  },
  {
    id: 'MEM-007',
    title: 'Redis Session Store Replication Lag',
    date: 'April 02, 2026',
    category: 'Infrastructure',
    service: 'Authentication Service',
    rootCause: 'Read-only Redis replicas lagged behind master node during automated key rotation cycle.',
    resolution: 'Pointed authentication middleware directly to Redis master and pre-warmed public key caches across edge nodes.',
    lesson: 'Enforce synchronous replication for security credential rotation across distributed caches.',
    impact: 'Intermittent 401 errors for 4,800 user sessions',
    relatedIncidents: ['INC-027'],
  },
  {
    id: 'MEM-004',
    title: 'Kafka Consumer Partition Unbalance',
    date: 'February 18, 2026',
    category: 'Infrastructure',
    service: 'Notification Worker',
    rootCause: 'Synchronous HTTP thread calls to downstream webhook provider blocked message ingestion loop.',
    resolution: 'Scaled worker replicas and refactored worker to decouple external HTTP calls from ingestion threads.',
    lesson: 'Never execute third-party API calls directly on the message bus ingestion thread.',
    impact: 'Queue backlog of 85,000 notifications delayed by 35 minutes',
    relatedIncidents: ['INC-026'],
  },
  {
    id: 'MEM-002',
    title: 'Kubernetes Ingress Controller Memory Pressure',
    date: 'January 10, 2026',
    category: 'Security',
    service: 'Ingress Gateway',
    rootCause: 'Unbounded header size in unauthenticated health check probe triggered worker container restart loop.',
    resolution: 'Added strict header size limit in ingress configuration and adjusted container memory limits.',
    lesson: 'Strictly validate maximum payload header limits at the perimeter proxy.',
    impact: 'Intermittent connection resets on ingress gateway for 8 minutes',
    relatedIncidents: ['INC-009'],
  },
];
